### ISSUE TITLE
Outras Informações

### ISSUE THREAD

**Issue by henriquezanfa** [centralufabc/ufabccentral#4]
Comecei a criar a tela de outras informações, com os seguintes dados:
- Senhas de Wi-Fi (ambos os campis)
- Acesso edoruam
- Horário da CAE
- Horário dos Achados e Perdidos
- Horários das bibliotecas
- Horário do RU

**Comment by rodrigo98rm** [comment]
Legal! Acho que estas são todas as informações mesmo.

Não precisa se preocupar muito com o layout, acho que por enquanto uma lista com cards contendo título e descrição da informação é suficiente.

Para acessar essa tela pode ser um botão na Home por enquanto. Depois colocamos isso em outro lugar.

**Comment by henriquezanfa** [comment]
Deixei mais ou menos com a mesma cara da versão do Central que está ativa hoje.

![image](https://user-images.githubusercontent.com/36772896/60816835-e9a7ad00-a170-11e9-846f-8f84cae0a46d.png)

**Comment by rodrigo98rm** [comment]
Muito bom!

Fiz algumas alterações e subi para o seu branch. O resultado final:

<img width="793" alt="Screen Shot 2019-07-13 at 18 18 18" src="https://user-images.githubusercontent.com/20744710/61176657-ca5ab680-a59a-11e9-92b2-972422cde74e.png">

**Comment by rodrigo98rm** [comment]
#5 PR merged! 🎉
